### ISSUE TITLE
Error when loading the mod

### ISSUE THREAD

**Issue by cyber-wojtek** [tizu69/ntl-redone#30]
Tried to load the mod v.1.19.2

[log](https://github.com/tizu69/ntl-redone/files/10527992/crash-2023-01-28_19.18.04-fml.txt)
screenshot
![screenshot](https://user-images.githubusercontent.com/69240079/215285156-2f232b28-c4e5-466b-b84b-97b366c056ce.png)

**Comment by tizu69** [comment]
NTL has been replaced by @rhysdh540 Unlimited.
