### ISSUE TITLE
QnA: HOW TO GET MOD

### ISSUE THREAD

**Issue by tizu69** [tizu69/ntl-redone#5]
Get mod here -> https://github.com/tizu69/ntl-redone/tags

Please back up your world! I do not fafing care if your world constantly crashes after using this. I'll look into crashes (please report!) but can't recover your world.

More questions and answers will be added soon, please ask small questions here if you don't think they deserve an extra issue.

---

Planned features

- Being able to dismount train from rails and drive anywhere (probably gonna take some time, my brain is tiny tbh)
- more to come

**Comment by zach2222** [comment]
How Do You Set The Settings On The Mod

**Comment by Shan-Min-69** [comment]
how do I use the mod on forge?
