### ISSUE TITLE
1.19 forge port

### ISSUE THREAD

**Issue by boppolopian** [tizu69/ntl-redone#8]
**To which version?**
Please specify target Create and Minecraft version as well as mod loader.

ohohoo oo forge....... oooo forge i love forge.... 1.19!!!!!!!!!!! ONE POINT NINETEEN!!!!!!!!!!!!!!!!!!!!!

**Comment by tizu69** [comment]
> Fabric support is coming in NTL 0.2 along with support for 1.19.2

_Originally posted by @tizu69 in https://github.com/tizu69/ntl-redone/issues/2#issuecomment-1366953227_

NTL 0.2 will have Fabric and Forge support for both 1.18.2 and 1.19.x.
